# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: adi-nata <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/24 18:59:58 by adi-nata          #+#    #+#              #
#    Updated: 2023/03/08 03:48:10 by adi-nata         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
		make -C ./ft_printf/
		make -C ./srcs/

clean:
		make clean -C ./ft_printf/
		make clean -C ./srcs/

fclean:
		make fclean -C ./ft_printf/
		make fclean -C ./srcs/